var tag = true;
if(tag){
	var meet_config={
		url:{
			//会议信息接口
			meet:'/gome-manager-web/meeting/queryMeetInfo',
			//子栏目背景图接口
			meetbg:'/gome-manager-web/meetManager/queryBackPic',
			//登录码登录接口
			signcode:'/gome-manager-web/meeting/validateMeetCode',
			//姓名登录接口
			sign:'/gome-manager-web/meetManager/signMeetJionPerson',
			//会议欢迎信接口
			welcome:'/gome-manager-web/meetManager/queryWelcomeLetter',
			//专家接口
			expert:'/gome-manager-web/professor/queryMeetingProfessor',
			//会议日程接口
			schedule:'/gome-manager-web/meetingSchedule/querySchedule',
			//会议资料接口
			data:'/gome-manager-web/meetingData/queryData',
			//发送邮箱接口
			senddata:'/gome-manager-web/meetingData/downloadFile',
			//获取我的提问接口
			getallask:'/gome-manager-web/meetingInteract/queryOwnHistory',
			//获取我最新提问接口
			getnewask:'/gome-manager-web/meetingInteract/queryOnWall',
			//发送提问接口
			ask:'/gome-manager-web/meetingInteract/addInteract',
			//发送投票接口
			vote:'/gome-manager-web/meetingVote/addVote',
			//是否已经投票接口
			isvote:'/gome-manager-web/meetingVote/queryPerVoteStatus',
			//是否可以投票接口
			canvote:'/gome-manager-web/meetingVote/queryVoteStatus',
			//获取会后反馈题目接口
			getfeedback:'/gome-manager-web/meetingSelect/querySelectResult',
			//是否已经提交问卷接口
			isfeedback:'/gome-manager-web/meetingSelect/queryPerSelectResult',
			//提交会后反馈接口
			feedback:'/gome-manager-web/meetingSelect/addSelect'
		}
	}
}else{
	var meet_config={
		url:{
			meet:'/json/signcode.js',
			signcode:'/json/signcode.js',
			sign:'/json/sign.js',
			welcome:'/json/welcome.js',
			expert:'/json/expert.js',
			schedule:'/json/schedule.js',
			data:'/json/data.js',
			senddata:'/json/data.js',
			getask:'/json/ask.js',
			ask:'/json/data.js',
			vote:'/json/data.js',
			isvote:'/json/data.js'
		}
	}
}

